export { default as About } from './about/About'
export { default as Footer } from './footer/Footer'
export { default as Home } from './home/Home'
export { default as Modules } from './modules/Modules'
export { default as Services } from './services/Services'
export { default as Navbar } from './navbar/Navbar'